# A varibale is an object that stores data

# 1. Global variable
# 2. Local or Task variable
# 3. User defined ( taking input from user)

- name: Print sample text
  hosts: localhost
  vars:
    URL_PLAY: I like my country
  tasks:
   - name: Print statement
     ansible.builtin.debug:
       msg: MESSAGE - {{ URL_PLAY }}
   - name: Print statement
     ansible.builtin.debug:
       msg: "{{ URL_PLAY }}"
   