# A varibale is an object that stores data

# 1. Global variable
# 2. Local or Task variable
# 3. User defined ( taking input from user)

- name: Print sample text
  hosts: localhost
  vars:
    URL_PLAY: I like my country
    dev: abc 
  tasks:
   - name: Print statement
     ansible.builtin.debug:
       msg: MESSAGE - {{ URL_PLAY }}
   - name: Print statement
     ansible.builtin.debug:
       msg: "{{ URL_PLAY }}"
   - name: Task variable
     ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
     vars:
        URL_TASK: tasks.example.com   
   - name: Print statement from user runtime
     ansible.builtin.debug:
       msg: "{{ URL_RUN }}" 
             

# ansible-playbook vars.yml -e "URL_RUN='I am printing this from my runtime'"       
    
   